Rename plot functions
UBC-MDS/strapR pull request #10
Opened 2022-01-25 06:06 UTC by zackt113

I have renamed the plot functions everywhere. And I also renamed the data_vis to display. Please help me to check if there is anything I missed. Much appreciated!

Zack

2022-01-27 22:07 UTC, voremargot commented
Looks good to me! I am happy to merge

2022-01-28 10:27 UTC, zackt113 commented
Hi, just added my function and test. I used ggplot2::ggplot so that I don't think I need to add any dependency. Let me know how's that looks. @gauthampughazhendhi @voremargot

2022-01-28 20:15 UTC, gauthampughazhendhi commented on R/plot_ci.R
> +  return(annotated_plot)
```suggestion
annotated_plot
```
I think you don't need `return` here, but please make sure you test it after making the change.

2022-01-28 20:16 UTC, gauthampughazhendhi requested changes
Looks good to me! I have only one change

2022-01-28 20:35 UTC, zackt113 commented
Fiixed it! And no problem with running tests

2022-01-28 20:45 UTC, voremargot reviewed
I was just formatting my functions and found some very tiny formatting things in your code! I think I found them all but you may want to check before we merge!

2022-01-28 20:45 UTC, voremargot commented on tests/testthat/test-plot_ci.R
> +                       n=100,
Fix formatting
```suggestion
                       n = 100, 
```

2022-01-28 20:45 UTC, voremargot commented on tests/testthat/test-plot_ci.R
> +                       n=100,
```suggestion
                       n = 100, 
```

2022-01-28 20:45 UTC, voremargot commented on tests/testthat/test-plot_ci.R
> +                       n=100,
```suggestion
                       n = 100, 
```

2022-01-28 20:45 UTC, voremargot commented on tests/testthat/test-plot_ci.R
> +                       n=100,
```suggestion
                       n = 100, 
```

2022-01-28 20:45 UTC, voremargot commented on R/plot_ci.R
> +#' plot_ci(c(1, 2, 3, 4, 5, 6, 7), 1000 ,n=100,
```suggestion
#' plot_ci(c(1, 2, 3, 4, 5, 6, 7), 1000, n = 100, 
```

2022-01-28 20:45 UTC, voremargot commented on R/plot_ci.R
> +#' plot_ci(c(1, 2, 3, 4, 5, 6, 7), 1000 ,n=100,
```suggestion
#' plot_ci(c(1, 2, 3, 4, 5, 6, 7), 1000, n = 100, 
```

2022-01-28 20:45 UTC, voremargot commented on README.Rmd
> +# plot_ci([1, 2, 3, 4, 5, 6, 7], 1000, n=100, ci_level=0.95, ci_random_seed=123)
```suggestion
# plot_ci([1, 2, 3, 4, 5, 6, 7], 1000, n = 100, ci_level = 0.95, ci_random_seed = 123)
```

2022-01-28 20:45 UTC, voremargot commented on README.md
> +# plot_ci([1, 2, 3, 4, 5, 6, 7], 1000, n=100, ci_level=0.95, ci_random_seed=123)
```suggestion
# plot_ci([1, 2, 3, 4, 5, 6, 7], 1000, n = 100, ci_level = 0.95, ci_random_seed = 123)
```

2022-01-28 21:11 UTC, merged